---
title: "The Ridge Regression"
author: "Shiyu Wang"
date: "`r Sys.Date()`"
output:
  html_document:
    self_contained: yes
    toc: true
---
<!--
%\VignetteEngine{knitr::rmarkdown}
%\VignetteIndexEntry{The ridge regression vignette}
-->
## The ridge_reg function
Ridge regression can be used to calculate coefficient vector given lambda and formula.
```{r}
library(bis557)
fit<-ridge_reg(Sepal.Length ~ .,1.2, iris)
fit
```
## Looks at effect on the out-of-sample mean square error as $\lambda$ varies
```{r}
data("ridge_train")
data("ridge_test")

# Calculate MSE
cal_mse<-function(formula,lambda,train_data,test_data){
  coeff<-ridge_reg(formula,lambda,train_data)
  x_test<-model.matrix(formula, test_set)
  y_test<-test_set[,as.character(formula)[2]]
  test_pred<-x_test %*% coeff
  mse<-mean(sum(y_test-test_pred)^2)
  mse
}

# infer the range of lambda values (get hints from Wenfeng Zhang, credits to him)
x<-model.matrix(y ~.,ridge_train)
svd_obj<-svd(x)
lbd_max<-max((svd_obj[["d"]])^2)
lambda<-seq(0,lbd_max,0.5)
mse_test<-sapply(lambda, function(lambda)cal_mse(y~.,lambda,ridge_train,ridge_test))
min(mse_test)

```



